### ISSUE TITLE
Upload new-type level to hackagedb

### ISSUE THREAD

**Issue by ingo-sander** [forsyde/type-level#1]
Should we upload the new type-level to hackagedb? Is it stable?

**Comment by ugeorge** [comment]
We could trust Travis to test whether it is stable. Up till now it seems to be stable with ghc-7.10.1, but not 8.0.1. I would increase the priority for this issue since uploading it to hakagedb would greatly ease integration with other libraries.

**Comment by ugeorge** [comment]
@HWoidt : Check the build status for my fork: [![Build Status](https://travis-ci.org/ugeorge/type-level.svg?branch=master)](https://travis-ci.org/ugeorge/type-level)

Could you take care of this, or should I also look into it?

**Comment by ugeorge** [comment]
The library is good to go, but I fear that in order to do a proper job a few things need to be attended:
- @ingo-sander: we need to publish the FSVec tutorial page mentioned in the README, which is not available any more. For now the link to a wiki is enough, and once we have a web site structure it might have its own page. Were can I find the old tutorial?
- the README and .cabal files need to be properly updated. I suggest pointing to this repository at the moment, while README could point to the wiki.

**Comment by ugeorge** [comment]
@2opremio @shaniaki could you please add me to the maintainers group on Hackagedb or update the type-level package?

The latest commit to master is sane: [![Build Status](https://travis-ci.org/forsyde/type-level.svg?branch=master)](https://travis-ci.org/forsyde/type-level).

**Comment by ugeorge** [comment]
It is done, and can be found [here](https://hackage.haskell.org/package/type-level-0.3.0). Thanks @shaniaki for adding me to the maintainer list.

I am reading in blogs that there might be some problems with HakagDB's haddock generators. Before closing this issue I shall wait until tomorrow to see if the documentation is there. Otherwise I will upload it manually.

**Comment by ugeorge** [comment]
Docs uploaded manually. Closing issue.
